import './HomePage.scss';

import { FC } from 'react';

const HomePage: FC = () => {
  return (
    <div className="gbs__border a">
      <div className='b'>FIX STYC</div>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Dignissimos temporibus ullam, porro quaerat commodi ab perspiciatis ratione architecto numquam deserunt? Id qui ex repellat magnam debitis facere sed aperiam sint eligendi omnis nisi nulla reprehenderit harum aliquid, suscipit sequi? Dolorum nisi culpa fugiat provident quo fuga quam veritatis porro id deserunt. Sunt nemo, labore illo officia eos excepturi delectus quae ab voluptatem at magnam quis obcaecati alias magni repellendus
      amet similique aliquam placeat consequuntur est. Ad provident alias, corporis mollitia non, obcaecati quas aperiam laudantium ducimus nam harum accusantium maiores dolorum laboriosam. Dicta iure dolores soluta sed facilis sapiente, fugit aperiam rerum deleniti delectus. Autem deleniti mollitia fuga, aspernatur sequi totam unde similique fugiat ducimus, eos corporis fugit saepe sapiente illo delectus doloribus harum voluptatibus ullam corrupti, natus at error doloremque. Dignissimos minus
      eaque laboriosam nulla voluptates magni enim ullam itaque recusandae impedit sapiente veritatis ipsa laudantium suscipit eligendi odio, sunt ducimus expedita numquam maxime vitae dolor assumenda vero reprehenderit. Repellendus consectetur quod totam in aut magni eaque deleniti necessitatibus nulla alias modi nostrum, adipisci excepturi, quam quasi eligendi sit ipsam veniam error cumque quisquam. Voluptatum commodi dicta hic tenetur reiciendis molestias suscipit quos obcaecati, inventore
      odit nostrum nisi distinctio nam doloremque at assumenda alias error consectetur veritatis reprehenderit ut corporis perspiciatis itaque? Deserunt non quisquam earum omnis obcaecati fugit autem ipsa iure labore sint ipsam, nam eveniet. Nisi dolorum rerum corporis aut ullam asperiores reprehenderit, fuga vel soluta dignissimos magni aspernatur eligendi repellendus quibusdam quo enim numquam ex vitae ipsa atque itaque beatae corrupti similique! Minus culpa amet maxime nihil enim ad ipsum
      iure atque architecto. Perferendis ad cupiditate ullam consequatur, ipsa neque laudantium itaque inventore eum voluptatem veritatis ex quod perspiciatis repellat quas, vel, in mollitia? Consectetur, explicabo reprehenderit. Dicta, cumque et id explicabo, architecto, eius fugit in tempora repellendus deleniti totam odit rerum? Quas facilis, quisquam tempore ab magnam similique in porro eum vero tenetur vel itaque neque inventore provident obcaecati sunt consectetur dolor animi dicta
      voluptates nihil fugiat? Autem ducimus sint doloribus porro minus? Magni cum doloribus voluptatem aspernatur voluptates ea nihil rerum beatae molestias natus repudiandae iure, quod necessitatibus inventore placeat nulla error tempora! Laboriosam at officia voluptates perspiciatis ut, quidem, in repellendus facere aut molestiae culpa distinctio possimus rerum laborum dignissimos error ducimus incidunt vitae doloribus asperiores consequatur tenetur nisi fuga perferendis! Cum sequi dolorem
      possimus iste aliquam, nesciunt similique omnis voluptates ducimus corporis, incidunt illo nam. Eos illo laudantium libero? Necessitatibus nisi reprehenderit veritatis accusantium accusamus adipisci doloremque laboriosam aut tempora quas sint voluptas voluptatibus omnis, nesciunt reiciendis aliquid ab, perferendis distinctio veniam repellendus qui cumque eos. Porro blanditiis in vitae repellendus molestiae ad. Accusantium itaque minima molestias atque enim? Eos laudantium molestias aut
      earum, eaque maxime placeat ipsa voluptate doloribus cupiditate numquam tempore consectetur unde debitis iure in porro quos praesentium amet odio! Et quidem aspernatur nulla nam, facilis excepturi autem ullam natus iure possimus, ipsa placeat perferendis labore quod atque quia hic nesciunt repellat reiciendis quisquam! Cumque placeat hic a quam aliquid temporibus recusandae aspernatur voluptate impedit at, earum expedita repudiandae beatae et ut voluptatibus eius quibusdam mollitia
      doloremque laboriosam? At illo praesentium, quod voluptatem necessitatibus facilis velit dolor iure. Error cupiditate molestias nostrum id asperiores eum doloremque blanditiis, natus consequuntur labore sunt adipisci dolores dolor nulla quam in officia laborum minus dolorem ipsum repudiandae omnis similique at fugit! Harum, praesentium. Deserunt, non error dolore porro expedita id eveniet provident dolorum. Natus sunt exercitationem tenetur autem ipsum quam quos consequatur laborum
      provident, explicabo cumque incidunt quod, magni repudiandae aut. Quas alias numquam vel dolore quos, nihil perferendis nesciunt eum consequatur sunt molestiae laborum sapiente consequuntur aliquid. Fugit exercitationem adipisci incidunt iste modi debitis ea! Accusamus quisquam unde ducimus consequatur quae sit quidem inventore? Repellendus suscipit vitae at eius. Delectus iusto cupiditate quos pariatur aperiam beatae officia repellendus natus hic corrupti nesciunt, corporis vel aut
      ducimus necessitatibus tempora. Impedit officiis, nostrum cupiditate eos nobis laboriosam eligendi fuga sed reprehenderit, minus temporibus. Provident blanditiis quia, voluptatum in illo, alias hic iusto odit impedit nemo libero, beatae nesciunt! Numquam fugiat consequuntur minima iste mollitia ducimus architecto, atque, accusantium nihil dolore deserunt, molestiae recusandae quos. Veniam quos eligendi dolore, quisquam sint facere laborum culpa ab omnis, at iste aliquid explicabo quod
      corporis recusandae nam error fuga perspiciatis eveniet aliquam quasi nemo? Sequi provident sed recusandae qui eaque maxime animi, vitae adipisci quod voluptates nemo voluptate maiores officia quos ut at atque, harum eveniet saepe. Tenetur, quae autem. Molestiae, fugiat dolorem facilis totam necessitatibus perferendis cupiditate suscipit impedit sapiente, eos iure, harum quia similique molestias doloremque! Maiores tenetur soluta delectus alias quasi dignissimos voluptate dolores
      perferendis illum doloribus debitis totam nam natus impedit dicta, vel eveniet ratione voluptatibus fugit minus distinctio similique libero? Aliquam doloremque consequuntur corrupti ratione minus exercitationem saepe aperiam! Nostrum, nisi molestias. Recusandae ducimus fugiat perspiciatis quos nobis enim! Ipsa in expedita odio numquam delectus, excepturi dignissimos aspernatur? Error eligendi nemo maiores sapiente quos ad, minima qui eius quam earum quisquam, veniam quaerat hic adipisci
      enim quo ipsam saepe rem id, nobis temporibus soluta quae voluptas? Corrupti animi similique autem tempora placeat impedit esse eaque harum, totam debitis quo? Sequi pariatur incidunt, magnam quis necessitatibus nihil, inventore accusantium natus neque nostrum nam hic alias quam magni illo vel deleniti, voluptas ipsam. Reprehenderit esse debitis labore? Quo quas cum et sit quidem, blanditiis quis tenetur est id voluptatum aliquid molestiae possimus beatae vel recusandae eligendi vitae iure
      quia. Fuga eveniet ea culpa officia repellat. Placeat error magnam autem ipsum accusantium cumque recusandae quasi, cupiditate, nulla veritatis aut eum quo aliquid, quod vero sint eius eligendi laudantium? Iusto unde deserunt, molestias tempore explicabo iste, ducimus adipisci fugiat vel pariatur, velit corrupti veniam voluptas ratione omnis atque eos saepe id voluptatem nam perspiciatis nisi qui beatae sequi. Ipsam, cupiditate, nostrum minima veritatis, neque voluptatibus quo aperiam
      corrupti eaque incidunt libero! Velit, doloribus. Reiciendis, possimus? Pariatur reprehenderit veniam deserunt commodi molestias beatae illum, ab porro consequatur rem quisquam earum qui nemo ducimus nostrum dolores debitis nulla reiciendis.
    </div>
  );
};

export default HomePage;
